### ISSUE TITLE
NSIndexSet+ASHelpers as_smallDescription fails after 4baf9bd commit

### ISSUE THREAD

**Issue by ItamarM** [facebook/AsyncDisplayKit#1944]
AsyncDisplayKit/Details/NSIndexSet+ASHelpers.m:73:72: error: format specifies type 'unsigned long' but the argument has type 'unsigned int' [-Werror,-Wformat]
[result appendFormat:@"%zu-%lu ", (unsigned long)range.location, NSMaxRange(range) - 1];
                                 ~~~                                   ^~~~~~~~~~~~~~~~~~~~~
                              


Making sense if you judging the commit (https://github.com/facebook/AsyncDisplayKit/commit/4baf9bdbfe2aedb77e5a066691820b823514dad2).
I think it formatted the wrong variable.
