### PR TITLE
[ASHelpers] Fix compiler warning in as_smallDescription on 32 bit

### LINKED ISSUE #1944: NSIndexSet+ASHelpers as_smallDescription fails after 4baf9bd commit
AsyncDisplayKit/Details/NSIndexSet+ASHelpers.m:73:72: error: format specifies type 'unsigned long' but the argument has type 'unsigned int' [-Werror,-Wformat]
[result appendFormat:@"%zu-%lu ", (unsigned long)range.location, NSMaxRange(range) - 1];
                                 ~~~                                   ^~~~~~~~~~~~~~~~~~~~~
                              


Making sense if you judging the commit (https://github.com/facebook/AsyncDisplayKit/commit/4baf9bdbfe2aedb77e5a066691820b823514dad2).
I think it formatted the wrong variable.

### PR DESCRIPTION
**Pull request by maicki**
Fixes #1944

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
Sweet!
